In [129]:
import pandas as pd

In [130]:
Data = pd.read_csv ("data_cleaning_sample.csv")
Data

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [5]:
Data.isnull ()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [6]:
Data.isnull ().sum ()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [9]:
print (Data.dropna ())
print ()
print (Data.dropna (axis = 1 ))

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [10]:
Data.fillna (0)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [11]:
Data["Age"].fillna ( Data["Age"].mean() )

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [12]:
Data.fillna (method = "ffill")

C:\Users\PRANAV\AppData\Local\Temp\ipykernel_13516\3210782523.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  Data.fillna (method = "ffill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [13]:
Data.fillna (method = 'bfill')

C:\Users\PRANAV\AppData\Local\Temp\ipykernel_13516\2502199109.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  Data.fillna (method = 'bfill')

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [14]:
Data.ffill ()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [15]:
Data.bfill ()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [16]:
Data.duplicated ()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [18]:
Data.drop_duplicates ()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [19]:
Data

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [21]:
Data.duplicated (subset = ["Gender"])

0    False
1    False
2     True
3     True
4     True
5     True
6     True
7     True
8     True
dtype: bool

In [27]:
Data.duplicated (subset = ["Name","Age"])

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [59]:
Data.dropna (subset = [  "Age"])

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
5    NaN  28.0        Delhi      F     eve@domain.com         NaN
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [77]:
D2 = Data.dropna ().copy ()

In [78]:
D2

    Name   Age         City Gender              Email   Join Date      Mature
0  Alice  25.0     New York      F  alice@example.com  01-05-2021      Mature
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020      Mature
4  David  22.0       Mumbai      M  david@example.com  12-11-2019  Not Mature
6  Alice  25.0     New York      F  alice@example.com  01-05-2021      Mature
7  Alice  25.0     New York      F  alice@example.com  01-05-2021      Mature

In [79]:
D2

    Name   Age         City Gender              Email   Join Date      Mature
0  Alice  25.0     New York      F  alice@example.com  01-05-2021      Mature
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020      Mature
4  David  22.0       Mumbai      M  david@example.com  12-11-2019  Not Mature
6  Alice  25.0     New York      F  alice@example.com  01-05-2021      Mature
7  Alice  25.0     New York      F  alice@example.com  01-05-2021      Mature

In [80]:
D2["Age"]  =  D2["Age"].astype (int)

In [81]:
D2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 7
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      object
 1   Age        5 non-null      int64
 2   City       5 non-null      object
 3   Gender     5 non-null      object
 4   Email      5 non-null      object
 5   Join Date  5 non-null      object
 6   Mature     5 non-null      object
dtypes: int64(1), object(6)
memory usage: 320.0+ bytes

In [82]:
# D2["Join Date"] = pd.to_datetime (D2["Join Date"])

In [83]:
D2

    Name  Age         City Gender              Email   Join Date      Mature
0  Alice   25     New York      F  alice@example.com  01-05-2021      Mature
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020      Mature
4  David   22       Mumbai      M  david@example.com  12-11-2019  Not Mature
6  Alice   25     New York      F  alice@example.com  01-05-2021      Mature
7  Alice   25     New York      F  alice@example.com  01-05-2021      Mature

In [84]:
D2["Name"] = D2["Name"].str.lower ()

In [85]:
D2

    Name  Age         City Gender              Email   Join Date      Mature
0  alice   25     New York      F  alice@example.com  01-05-2021      Mature
2    bob   30  Los Angeles      M    bob@example.com  15-06-2020      Mature
4  david   22       Mumbai      M  david@example.com  12-11-2019  Not Mature
6  alice   25     New York      F  alice@example.com  01-05-2021      Mature
7  alice   25     New York      F  alice@example.com  01-05-2021      Mature

In [86]:
D2["City"].str.contains ("New York" , case = "False")

0     True
2    False
4    False
6     True
7     True
Name: City, dtype: bool

In [87]:
D2

    Name  Age         City Gender              Email   Join Date      Mature
0  alice   25     New York      F  alice@example.com  01-05-2021      Mature
2    bob   30  Los Angeles      M    bob@example.com  15-06-2020      Mature
4  david   22       Mumbai      M  david@example.com  12-11-2019  Not Mature
6  alice   25     New York      F  alice@example.com  01-05-2021      Mature
7  alice   25     New York      F  alice@example.com  01-05-2021      Mature

In [88]:
D2["Email"].str.split ("@")

0    [alice, example.com]
2      [bob, example.com]
4    [david, example.com]
6    [alice, example.com]
7    [alice, example.com]
Name: Email, dtype: object

In [99]:
Data

,Name,Age,City,Gender,Email,Join Date,Mature
0,Alice,25.0,New York,NaN,alice@example.com,01-05-2021,Mature
1,Charlie,NaN,Delhi,NaN,charlie@example,20-07-2021,Not Mature
2,Bob,30.0,Los Angeles,NaN,bob@example.com,15-06-2020,Mature
3,Charlie,NaN,Delhi,NaN,charlie@example,20-07-2021,Not Mature
4,David,22.0,Mumbai,NaN,david@example.com,12-11-2019,Not Mature
5,NaN,28.0,Delhi,NaN,eve@domain.com,NaN,Mature
6,Alice,25.0,New York,NaN,alice@example.com,01-05-2021,Mature
7,Alice,25.0,New York,NaN,alice@example.com,01-05-2021,Mature
8,Charlie,NaN,Delhi,NaN,charlie@example,20-07-2021,Not Mature

In [100]:
Data ["Mature"]= Data ["Age"].apply (lambda x : "Mature" if x >= 25 else "Not Mature")

def A (x) :
    if x >= 25 :
        return "Mature"
    else :
        return "Not Mature"

Data ["Age"].apply (A)

0        Mature
1    Not Mature
2        Mature
3    Not Mature
4    Not Mature
5        Mature
6        Mature
7        Mature
8    Not Mature
Name: Age, dtype: object

In [101]:
Data

,Name,Age,City,Gender,Email,Join Date,Mature
0,Alice,25.0,New York,NaN,alice@example.com,01-05-2021,Mature
1,Charlie,NaN,Delhi,NaN,charlie@example,20-07-2021,Not Mature
2,Bob,30.0,Los Angeles,NaN,bob@example.com,15-06-2020,Mature
3,Charlie,NaN,Delhi,NaN,charlie@example,20-07-2021,Not Mature
4,David,22.0,Mumbai,NaN,david@example.com,12-11-2019,Not Mature
5,NaN,28.0,Delhi,NaN,eve@domain.com,NaN,Mature
6,Alice,25.0,New York,NaN,alice@example.com,01-05-2021,Mature
7,Alice,25.0,New York,NaN,alice@example.com,01-05-2021,Mature
8,Charlie,NaN,Delhi,NaN,charlie@example,20-07-2021,Not Mature

In [115]:

Dict = { "F" : "Female",
       "M" : "Male" ,
       "O" : "Other" }

Data ["Gender"] = Data["Gender"].map (Dict)

In [116]:
Data

Empty DataFrame
Columns: [Name, Age, City, Gender, Email, Join Date, Mature]
Index: []

In [131]:
D1 = Data.copy ()

In [120]:
D1 = D1.dropna ()

In [125]:
type (D1["Gender"])

pandas.core.series.Series

In [126]:
D1.info ()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      object
 1   Age        5 non-null      float64
 2   City       5 non-null      object
 3   Gender     5 non-null      object
 4   Email      5 non-null      object
 5   Join Date  5 non-null      object
dtypes: float64(1), object(5)
memory usage: 280.0+ bytes

In [132]:
D1["Gender"] = D1["Gender"].map ({
    "F" : "Female",
    "M" : "Male" ,
    "O" : "Others" 
})

In [133]:
D1

      Name   Age         City  Gender              Email   Join Date
0    Alice  25.0     New York  Female  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021
4    David  22.0       Mumbai    Male  david@example.com  12-11-2019
5      NaN  28.0        Delhi  Female     eve@domain.com         NaN
6    Alice  25.0     New York  Female  alice@example.com  01-05-2021
7    Alice  25.0     New York  Female  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021

In [ ]:
D1["City"] = D1["City"].crete