In [4]:
import pandas as pd 
Data = pd.read_csv ("Movie.csv") 
Data.columns = Data.columns.str.strip () 
Data

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
2,Amir khan,Dangal,2016,Biological,2024,9.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8

In [5]:
Data.sort_values ("Year")

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
2,Amir khan,Dangal,2016,Biological,2024,9.2
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
0,shak ruk khan,Pathan,2023,Action,1050,7.2

In [21]:
Data.sort_values ("Box Office (NR Cross)" , ascending=False , inplace = True )

In [19]:
Data.sort_values (["Year","IMDB"] , ascending = False  ) 
Data

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
2,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
3,Hritik Roshan,War,2019,Action,180,7.6
4,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Ayushman kurana,Padmawat,2018,Historical,585,8.0
7,salmankhan,Tiger zindya he,2017,Action,565,8.0
8,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8
9,Amir khan,Dangal,2016,Biological,2024,9.2

In [13]:
Data .reset_index ()

,index,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
2,8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
3,6,Hritik Roshan,War,2019,Action,180,7.6
4,7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
5,5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
7,1,salmankhan,Tiger zindya he,2017,Action,565,8.0
8,9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8
9,2,Amir khan,Dangal,2016,Biological,2024,9.2

In [14]:
Data.reset_index (drop = True)

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
2,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
3,Hritik Roshan,War,2019,Action,180,7.6
4,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Ayushman kurana,Padmawat,2018,Historical,585,8.0
7,salmankhan,Tiger zindya he,2017,Action,565,8.0
8,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8
9,Amir khan,Dangal,2016,Biological,2024,9.2

In [15]:
Data.sort_index ()

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
2,Amir khan,Dangal,2016,Biological,2024,9.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8

In [23]:
Data.reset_index (drop = True , inplace = True)

In [24]:
Data

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,Amir khan,Dangal,2016,Biological,2024,9.2
1,shak ruk khan,Pathan,2023,Action,1050,7.2
2,Ayushman kurana,Padmawat,2018,Historical,585,8.0
3,salmankhan,Tiger zindya he,2017,Action,565,8.0
4,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
5,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
6,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8
7,Hritik Roshan,War,2019,Action,180,7.6
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
9,Rajkummar rao,Stree,2018,Horror,111,8.2

In [27]:
Data["Rank"] = Data ["Year"].rank ()

In [45]:
Data["Rank"] = Data ["Year"].rank (ascending = False , method = 'dense')

In [41]:
Data["Rank"] = Data ["Year"].rank (method = "dense")

In [32]:
Data.rename (columns = {"Actor" : "Name" , "Rank" : "Rating"} , inplace = True)

In [34]:
Data.rename (index = {0 : "Row 0"} , inplace = True)

In [46]:
Data

,Name,Film,Year,Gener,Box Office (NR Cross),IMDB,Rating,Rank
Row 0,Amir khan,Dangal,2016,Biological,2024,9.2,10.0,6.0
1,shak ruk khan,Pathan,2023,Action,1050,7.2,1.0,1.0
2,Ayushman kurana,Padmawat,2018,Historical,585,8.0,6.5,4.0
3,salmankhan,Tiger zindya he,2017,Action,565,8.0,8.5,5.0
4,Ranvir kapoor,Animan,2022,Fantasy,431,9.0,2.5,2.0
5,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7,4.5,3.0
6,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8,8.5,5.0
7,Hritik Roshan,War,2019,Action,180,7.6,4.5,3.0
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7,2.5,2.0
9,Rajkummar rao,Stree,2018,Horror,111,8.2,6.5,4.0

In [36]:
Data [["Name" , "Rating" , "Year"]]

                  Name  Rating  Year
Row 0       Amir khan     10.0  2016
1        shak ruk khan     1.0  2023
2      Ayushman kurana     6.5  2018
3          salmankhan      8.5  2017
4        Ranvir kapoor     2.5  2022
5         Akshay Kumar     4.5  2019
6           VsrunDawan     8.5  2017
7        Hritik Roshan     4.5  2019
8        Kartik Aaryan     2.5  2022
9       Rajkummar rao      6.5  2018

In [39]:
Col = ["Rating"] + [x for x in Data.columns if x != "Rating"]
Data [Col]

,Rating,Name,Film,Year,Gener,Box Office (NR Cross),IMDB
Row 0,10.0,Amir khan,Dangal,2016,Biological,2024,9.2
1,1.0,shak ruk khan,Pathan,2023,Action,1050,7.2
2,6.5,Ayushman kurana,Padmawat,2018,Historical,585,8.0
3,8.5,salmankhan,Tiger zindya he,2017,Action,565,8.0
4,2.5,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
5,4.5,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
6,8.5,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8
7,4.5,Hritik Roshan,War,2019,Action,180,7.6
8,2.5,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
9,6.5,Rajkummar rao,Stree,2018,Horror,111,8.2