# create Dataframe using list

In [1]:
import pandas as pd

In [6]:
data = [["Sushil" , 91],
       ["Rohit" , 99] ,
       [ "Ganesh", 71],
       ["yash" , 55]] 
data

[['Sushil', 91], ['Rohit', 99], ['Ganesh', 71], ['yash', 55]]

In [7]:
df = pd.DataFrame (data , columns = ["Name" , "Marks"])
df

     Name  Marks
0  Sushil     91
1   Rohit     99
2  Ganesh     71
3    yash     55

# Create Dataframe from dict and list

In [8]:
D2 = pd.DataFrame ({
    'name' : ['Sushil' , 'Alisa' , 'Mishra'] ,
    'marks' : [94,76,99] 
     })
D2

     name  marks
0  Sushil     94
1   Alisa     76
2  Mishra     99

# Create Dataframe from numpy array

In [9]:
import numpy as np

In [10]:
A = np.array ([[1,2],
               [3,4]])

In [12]:
D3 = pd.DataFrame (A, columns = ["A", "B"])

In [13]:
D3

   A  B
0  1  2
1  3  4

# Create and Read Data From Excel

In [15]:
D4 = pd.read_excel ('Excel_Data.xlsx')
D4

       Name  Marks  age
0    Sushil     90   55
1    Ganesh     78   33
2    Rohit      57   44
3     Rohan     98   66
4   Pranav      67   88
5   Vandhu      78   55
6   Vishal      97   33
7     Rani      56   44
8  krishana     87   66
9   utamrao     98   88

# Create and read Data frame from CSV file

In [16]:
D5 = pd.read_csv ('Csv_Data.csv')

In [17]:
D5

       Name  Marks  age
0    Sushil     90   55
1    Ganesh     78   33
2    Rohit      57   44
3     Rohan     98   66
4   Pranav      67   88
5   Vandhu      78   55
6   Vishal      97   33
7     Rani      56   44
8  krishana     87   66
9   utamrao     98   88

# read data from json

In [19]:
D6 = pd.read_json ("Json_Data.json")

In [20]:
D6

     name  Marks
0  Sushil     99
1  pranav     55

# read from website

In [23]:
D7 = pd.read_csv ("http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")

In [24]:
D7

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

# EDA on D7

In [26]:
D7

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [27]:
D7.head ()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [29]:
D7.tail ()

     5.1  3.5  1.4  0.2     Iris-setosa
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

In [30]:
D7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   5.1          149 non-null    float64
 1   3.5          149 non-null    float64
 2   1.4          149 non-null    float64
 3   0.2          149 non-null    float64
 4   Iris-setosa  149 non-null    object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB

In [31]:
D7.describe ()

              5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [34]:
D7.columns

Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')

In [35]:
D7.shape

(149, 5)