In [1]:
import pandas as pd

In [2]:
Data = pd.read_csv ('Movie.csv')

In [16]:
print (Data.columns)
Data.columns = Data.columns.str.strip () 
print (Data.columns)

Data

Index(['Actor', 'Film', 'Year', 'Gener', 'Box Office (NR Cross)', 'IMDB'], dtype='object')
Index(['Actor', 'Film', 'Year', 'Gener', 'Box Office (NR Cross)', 'IMDB'], dtype='object')

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
2,Amir khan,Dangal,2016,Biological,2024,9.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8

# Filter by condition

In [4]:
Data [Data["IMDB"] >= 8]

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
2,Amir khan,Dangal,2016,Biological,2024,9.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2

In [8]:
Data [Data['IMDB'] >= 7] ["Film"] # Only give name of Film

0              Pathan
1    Tiger zindya he
2              Dangal
3              Animan
4            Padmawat
5               Stree
6                 War
8      bhool boolya 2
Name: Film, dtype: object

In [25]:
Data [ (Data['IMDB'] >= 8) & (Data["Year"] > 2017)  ] ["Actor"] # Single Column select

3      Ranvir kapoor
4    Ayushman kurana
5     Rajkummar rao
Name: Actor, dtype: object

In [45]:
Data [ (Data['IMDB'] >= 8) & (Data["Year"] > 2017) ]  [ ["Actor","Film"] ] # Multiple column select

             Actor      Film
3    Ranvir kapoor    Animan
4  Ayushman kurana  Padmawat
5   Rajkummar rao      Stree

# query () Function Easy filter

In [32]:
Data .query ("IMDB >= 7")

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
2,Amir khan,Dangal,2016,Biological,2024,9.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Hritik Roshan,War,2019,Action,180,7.6
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7

In [43]:
Data.query ('IMDB >= 8 & Year >= 2017' )

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2

In [35]:
Data.query ("IMDB >= 8 and Year > 2017")[["Film" ,"IMDB" ,'Actor']]

       Film  IMDB            Actor
3    Animan   9.0    Ranvir kapoor
4  Padmawat   8.0  Ayushman kurana
5     Stree   8.2   Rajkummar rao

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
2,Amir khan,Dangal,2016,Biological,2024,9.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8