In [49]:
import pandas as pd

In [50]:
D = pd.read_csv ("Movie.csv")

In [51]:
df = D

In [52]:
df

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
2,Amir khan,Dangal,2016,Biological,2024,9.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8

# Select aa columan

In [53]:
df.columns

Index(['Actor ', 'Film', 'Year ', 'Gener', 'Box Office (NR Cross)', 'IMDB'], dtype='object')

In [54]:
df.columns = df.columns.str.strip()

In [55]:
df ['Actor']

0      shak ruk khan
1        salmankhan
2         Amir khan
3      Ranvir kapoor
4    Ayushman kurana
5     Rajkummar rao
6      Hritik Roshan
7       Akshay Kumar
8      Kartik Aaryan
9         VsrunDawan
Name: Actor, dtype: object

In [56]:
df [['Actor','Film','IMDB']]

             Actor                Film  IMDB
0    shak ruk khan              Pathan   7.2
1      salmankhan     Tiger zindya he    8.0
2       Amir khan               Dangal   9.2
3    Ranvir kapoor              Animan   9.0
4  Ayushman kurana            Padmawat   8.0
5   Rajkummar rao                Stree   8.2
6    Hritik Roshan                 War   7.6
7     Akshay Kumar          Good Newaz   6.7
8    Kartik Aaryan      bhool boolya 2   7.7
9       VsrunDawan  Badhri ki dulaniya   4.8

In [119]:
df ['Actor'][0] # That apply on single column

'shak ruk khan'

# Return Row Separated Data

In [58]:
df.loc [0]

Actor                    shak ruk khan
Film                            Pathan
Year                              2023
Gener                          Action
Box Office (NR Cross)             1050
IMDB                               7.2
Name: 0, dtype: object

In [59]:
type (df.loc [0])

pandas.core.series.Series

In [60]:
D2 = df.copy() # It normal create View

In [61]:
D2.index =  ['A',"B","C","D","E","F","G","H","I","J"]

In [63]:
D2

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
A,shak ruk khan,Pathan,2023,Action,1050,7.2
B,salmankhan,Tiger zindya he,2017,Action,565,8.0
C,Amir khan,Dangal,2016,Biological,2024,9.2
D,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
E,Ayushman kurana,Padmawat,2018,Historical,585,8.0
F,Rajkummar rao,Stree,2018,Horror,111,8.2
G,Hritik Roshan,War,2019,Action,180,7.6
H,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
I,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
J,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8

In [65]:
# D2.loc [0] # Return Error
D2.loc ['A']

Actor                    shak ruk khan
Film                            Pathan
Year                              2023
Gener                          Action
Box Office (NR Cross)             1050
IMDB                               7.2
Name: A, dtype: object

In [69]:
D2.iloc [0]
# D2.iloc ['A'] # Error

Actor                    shak ruk khan
Film                            Pathan
Year                              2023
Gener                          Action
Box Office (NR Cross)             1050
IMDB                               7.2
Name: A, dtype: object

## Access Cell

In [71]:
df

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
2,Amir khan,Dangal,2016,Biological,2024,9.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8

In [72]:
df.loc [3,'Film'] # import cell

'Animan'

In [77]:
df.iloc [3,1]

'Animan'

# Access row wise multiple columns

In [76]:
df.loc [5 , ["Actor" ,"Film","IMDB"]]

Actor    Rajkummar rao
Film              Stree
IMDB                8.2
Name: 5, dtype: object

In [78]:
df.iloc [5 ,[0,1,2]]

Actor    Rajkummar rao
Film              Stree
Year               2018
Name: 5, dtype: object

# Slicing

In [79]:
df.loc [0:3 ,["Actor" ,"Film"]] # last element count

           Actor              Film
0  shak ruk khan            Pathan
1    salmankhan   Tiger zindya he
2     Amir khan             Dangal
3  Ranvir kapoor            Animan

In [80]:
df.iloc [0:3 ,[0,1]] # it like range last element not count

           Actor              Film
0  shak ruk khan            Pathan
1    salmankhan   Tiger zindya he
2     Amir khan             Dangal

In [92]:
D3 = df.loc [0:3 , ['Film','IMDB']] # Return Copy not view 
print ("Created DF = \n" , D3)

Created DF =
                Film  IMDB
0            Pathan   7.2
1  Tiger zindya he    8.0
2            Dangal   9.2
3            Animan   9.0

In [93]:
D3.index = ["A" ,"B" ,"C","D"]
print ("Modify DF : \n" , D3)

Modify DF :
                Film  IMDB
A            Pathan   7.2
B  Tiger zindya he    8.0
C            Dangal   9.2
D            Animan   9.0

In [91]:
print ("OLd DF ARE CHANGED OR NOT : \n", df)

OLd DF ARE CHANGED OR NOT :
              Actor                Film  Year            Gener  \
0    shak ruk khan              Pathan  2023          Action
1      salmankhan     Tiger zindya he   2017          Action
2       Amir khan               Dangal  2016       Biological
3    Ranvir kapoor              Animan  2022         Fantasy
4  Ayushman kurana            Padmawat  2018      Historical
5   Rajkummar rao                Stree  2018           Horror
6    Hritik Roshan                 War  2019          Action
7     Akshay Kumar          Good Newaz  2019          Comedy
8    Kartik Aaryan      bhool boolya 2  2022    Comedy Horror
9       VsrunDawan  Badhri ki dulaniya  2017  Romantic comedy

   Box Office (NR Cross)  IMDB
0                   1050   7.2
1                    565   8.0
2                   2024   9.2
3                    431   9.0
4                    585   8.0
5                    111   8.2
6                    180   7.6
7                    318   6.7
8                    166   7.7
9                    201   4.8

# At() to import single cell

In [100]:
df.at [0 , 'Actor'] # It speed fast than loc

'shak ruk khan'

In [108]:
import time

In [117]:
start = time.time () 
df.loc [7 , "IMDB"] 
end = time.time () 

print ("loc time = " , end - start)

loc time =  0.000911712646484375

In [118]:
start = time.time () 
df.at [7 , "IMDB"] 
end = time.time () 

print ("at time = " , end - start)

at time =  0.0003559589385986328