# Data Transformation

Once Data chean then reshape , reformat and reordered .

In [1]:
import pandas as pd

In [2]:
Data = pd.read_csv ("Movie.csv")

In [3]:
Data.columns = Data.columns.str.strip () 

Data

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
2,Amir khan,Dangal,2016,Biological,2024,9.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8

In [4]:
Data.sort_values ("Year")

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
2,Amir khan,Dangal,2016,Biological,2024,9.2
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
0,shak ruk khan,Pathan,2023,Action,1050,7.2

In [5]:
Data.sort_values ("Year" ,ascending = False)

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8
2,Amir khan,Dangal,2016,Biological,2024,9.2

In [6]:
D2 = Data.sort_values (["Year" , "IMDB"]).copy ()   
D2

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
2,Amir khan,Dangal,2016,Biological,2024,9.2
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
6,Hritik Roshan,War,2019,Action,180,7.6
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
0,shak ruk khan,Pathan,2023,Action,1050,7.2

# reordering

In [7]:
D2

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
2,Amir khan,Dangal,2016,Biological,2024,9.2
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
6,Hritik Roshan,War,2019,Action,180,7.6
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
0,shak ruk khan,Pathan,2023,Action,1050,7.2

In [8]:
D2.reset_index () # Return a copy

,index,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,2,Amir khan,Dangal,2016,Biological,2024,9.2
1,9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8
2,1,salmankhan,Tiger zindya he,2017,Action,565,8.0
3,4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
4,5,Rajkummar rao,Stree,2018,Horror,111,8.2
5,7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
6,6,Hritik Roshan,War,2019,Action,180,7.6
7,8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
8,3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
9,0,shak ruk khan,Pathan,2023,Action,1050,7.2

In [9]:
D2.reset_index (drop=True)  # drop index column

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,Amir khan,Dangal,2016,Biological,2024,9.2
1,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8
2,salmankhan,Tiger zindya he,2017,Action,565,8.0
3,Ayushman kurana,Padmawat,2018,Historical,585,8.0
4,Rajkummar rao,Stree,2018,Horror,111,8.2
5,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
6,Hritik Roshan,War,2019,Action,180,7.6
7,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
8,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
9,shak ruk khan,Pathan,2023,Action,1050,7.2

In [10]:
D2.reset_index ( drop=True , inplace=True) # Change original D2 |

In [11]:
D2

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,Amir khan,Dangal,2016,Biological,2024,9.2
1,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8
2,salmankhan,Tiger zindya he,2017,Action,565,8.0
3,Ayushman kurana,Padmawat,2018,Historical,585,8.0
4,Rajkummar rao,Stree,2018,Horror,111,8.2
5,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
6,Hritik Roshan,War,2019,Action,180,7.6
7,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
8,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
9,shak ruk khan,Pathan,2023,Action,1050,7.2

In [12]:
D2.sort_index ()

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,Amir khan,Dangal,2016,Biological,2024,9.2
1,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8
2,salmankhan,Tiger zindya he,2017,Action,565,8.0
3,Ayushman kurana,Padmawat,2018,Historical,585,8.0
4,Rajkummar rao,Stree,2018,Horror,111,8.2
5,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
6,Hritik Roshan,War,2019,Action,180,7.6
7,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
8,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
9,shak ruk khan,Pathan,2023,Action,1050,7.2

# Ranking

In [13]:
D2["IMDB"].rank ()

0    10.0
1     1.0
2     6.5
3     6.5
4     8.0
5     2.0
6     4.0
7     5.0
8     9.0
9     3.0
Name: IMDB, dtype: float64

In [14]:
D2["Rank"] = D2["IMDB"].rank (ascending = False) # high value low Rank

In [16]:
D2["Rank"] = D2["IMDB"] .rank (ascending = False , method = "dense") # Same Rank to Same IMDB Score

In [17]:
D2

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB,Rank
0,Amir khan,Dangal,2016,Biological,2024,9.2,1.0
1,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8,9.0
2,salmankhan,Tiger zindya he,2017,Action,565,8.0,4.0
3,Ayushman kurana,Padmawat,2018,Historical,585,8.0,4.0
4,Rajkummar rao,Stree,2018,Horror,111,8.2,3.0
5,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7,8.0
6,Hritik Roshan,War,2019,Action,180,7.6,6.0
7,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7,5.0
8,Ranvir kapoor,Animan,2022,Fantasy,431,9.0,2.0
9,shak ruk khan,Pathan,2023,Action,1050,7.2,7.0

# rename column and row

In [18]:
D2

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB,Rank
0,Amir khan,Dangal,2016,Biological,2024,9.2,1.0
1,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8,9.0
2,salmankhan,Tiger zindya he,2017,Action,565,8.0,4.0
3,Ayushman kurana,Padmawat,2018,Historical,585,8.0,4.0
4,Rajkummar rao,Stree,2018,Horror,111,8.2,3.0
5,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7,8.0
6,Hritik Roshan,War,2019,Action,180,7.6,6.0
7,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7,5.0
8,Ranvir kapoor,Animan,2022,Fantasy,431,9.0,2.0
9,shak ruk khan,Pathan,2023,Action,1050,7.2,7.0

In [21]:
D2.rename (columns = {"Actor" : "Name"}) 
D2.rename (columns = {"Actor" : "Name"} , inplace = True)
D2

,Name,Film,Year,Gener,Box Office (NR Cross),IMDB,Rank
0,Amir khan,Dangal,2016,Biological,2024,9.2,1.0
1,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8,9.0
2,salmankhan,Tiger zindya he,2017,Action,565,8.0,4.0
3,Ayushman kurana,Padmawat,2018,Historical,585,8.0,4.0
4,Rajkummar rao,Stree,2018,Horror,111,8.2,3.0
5,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7,8.0
6,Hritik Roshan,War,2019,Action,180,7.6,6.0
7,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7,5.0
8,Ranvir kapoor,Animan,2022,Fantasy,431,9.0,2.0
9,shak ruk khan,Pathan,2023,Action,1050,7.2,7.0

In [24]:
D2.rename (index = {1:"Key 1", 2 : "Key 2"}  , inplace = True ) 
D2

,Name,Film,Year,Gener,Box Office (NR Cross),IMDB,Rank
0,Amir khan,Dangal,2016,Biological,2024,9.2,1.0
Key 1,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8,9.0
Key 2,salmankhan,Tiger zindya he,2017,Action,565,8.0,4.0
3,Ayushman kurana,Padmawat,2018,Historical,585,8.0,4.0
4,Rajkummar rao,Stree,2018,Horror,111,8.2,3.0
5,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7,8.0
6,Hritik Roshan,War,2019,Action,180,7.6,6.0
7,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7,5.0
8,Ranvir kapoor,Animan,2022,Fantasy,431,9.0,2.0
9,shak ruk khan,Pathan,2023,Action,1050,7.2,7.0

# Rearranging Columns

In [25]:
D2 [["Name" , "Film" ,"Gener"]]

                  Name                Film            Gener
0           Amir khan               Dangal       Biological
Key 1       VsrunDawan  Badhri ki dulaniya  Romantic comedy
Key 2      salmankhan     Tiger zindya he           Action
3      Ayushman kurana            Padmawat      Historical
4       Rajkummar rao                Stree           Horror
5         Akshay Kumar          Good Newaz          Comedy
6        Hritik Roshan                 War          Action
7        Kartik Aaryan      bhool boolya 2    Comedy Horror
8        Ranvir kapoor              Animan         Fantasy
9        shak ruk khan              Pathan          Action

In [26]:
cols = ["Year"] + [x for x in D2.columns if x != "Year"]
D2 [cols]

,Year,Name,Film,Gener,Box Office (NR Cross),IMDB,Rank
0,2016,Amir khan,Dangal,Biological,2024,9.2,1.0
Key 1,2017,VsrunDawan,Badhri ki dulaniya,Romantic comedy,201,4.8,9.0
Key 2,2017,salmankhan,Tiger zindya he,Action,565,8.0,4.0
3,2018,Ayushman kurana,Padmawat,Historical,585,8.0,4.0
4,2018,Rajkummar rao,Stree,Horror,111,8.2,3.0
5,2019,Akshay Kumar,Good Newaz,Comedy,318,6.7,8.0
6,2019,Hritik Roshan,War,Action,180,7.6,6.0
7,2022,Kartik Aaryan,bhool boolya 2,Comedy Horror,166,7.7,5.0
8,2022,Ranvir kapoor,Animan,Fantasy,431,9.0,2.0
9,2023,shak ruk khan,Pathan,Action,1050,7.2,7.0