# Merge ()

In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [3]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [5]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [6]:
pd.merge (employees , departments , on = "DeptID") # inner join

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [8]:
pd.merge (employees , departments , on = "DeptID" , how = "left")  # Left Join

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [10]:
pd.merge (employees , departments , on = "DeptID" , how = "right")

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [12]:
pd.merge (employees , departments , on = "DeptID" , how = "outer") # Full Outer Join

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

# concat ()

In [13]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})

In [14]:
df1

    Name
0  Alice
1    Bob

In [15]:
df2

      Name
0  Charlie
1    David

In [18]:
pd.concat ( [df1 , df2 ] )

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [19]:
pd .concat ([df1 , df2] , axis = 1 )

    Name     Name
0  Alice  Charlie
1    Bob    David

In [20]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"] ,
                   "Score" : [99 , 97]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"],
                   "Age" : [20,31]})

In [21]:
df1

    Name  Score
0  Alice     99
1    Bob     97

In [22]:
df2

      Name  Age
0  Charlie   20
1    David   31

In [23]:
pd.concat ([df1 , df2 ] )

      Name  Score   Age
0    Alice   99.0   NaN
1      Bob   97.0   NaN
0  Charlie    NaN  20.0
1    David    NaN  31.0

In [24]:
pd.concat ([df1 , df2] , axis = 1 )

    Name  Score     Name  Age
0  Alice     99  Charlie   20
1    Bob     97    David   31