In [1]:
import pandas as pd

# 1 CSV

In [4]:
D1 = pd .read_csv ("Csv_Data.csv")
D1

       Name  Marks  age
0    Sushil     90   55
1    Ganesh     78   33
2    Rohit      57   44
3     Rohan     98   66
4   Pranav      67   88
5   Vandhu      78   55
6   Vishal      97   33
7     Rani      56   44
8  krishana     87   66
9   utamrao     98   88

In [8]:
D1 = D1.query ("Marks > 80" ) 
D1

       Name  Marks  age
0    Sushil     90   55
3     Rohan     98   66
6   Vishal      97   33
8  krishana     87   66
9   utamrao     98   88

In [11]:
D1.to_csv ( "Mark_high.csv")

In [14]:
D1.to_csv ("Mark_high_without_index.csv" , index = False) # without index

# Excel

In [17]:
D1 = pd .read_excel ("Sample.xlsx") 
D1

   Unnamed: 0      Name  Marks  age
0           0    Sushil     90   55
1           3     Rohan     98   66
2           6   Vishal      97   33
3           8  krishana     87   66
4           9   utamrao     98   88

In [20]:
D2 = pd.read_excel ("Sample.xlsx" , sheet_name = "Sheet1") 
D2

   Marks  age
0     90   55
1     98   66
2     97   33
3     87   66
4     98   88

In [21]:
D2.to_excel ("Sample1.xlsx" , index = False)

In [28]:
with pd.ExcelWriter("Sample2.xlsx") as E :
    D2.to_excel (E , sheet_name = "S1" , index = False)
    D1.to_excel (E, sheet_name = "S2" , index = False)

# Json

In [40]:
data = [
    {"id": 1, "name": "Alice", "address": {"city": "Delhi", "zipcode": "110001"}},
    {"id": 2, "name": "Bob", "address": {"city": "Mumbai", "zipcode": "400001"}}
]

In [41]:
D1 = pd .json_normalize (data)

In [42]:
D1

   id   name address.city address.zipcode
0   1  Alice        Delhi          110001
1   2    Bob       Mumbai          400001