# Lecture 1

In [1]:
import pandas as pd

In [2]:
pd.DataFrame ({
    "name": ["A","B"],
    "age" : [22 , 25]
    })

  name  age
0    A   22
1    B   25

# Lecture 2 Core DS

In [5]:
D1 = pd.Series ( [1,2,3] , index= ["A","B","C"] ) 
D1

A    1
B    2
C    3
dtype: int64

In [6]:
D2 = pd.DataFrame ({
    "name" : ["A" , "B"],
    "Age" : [22,25]
}) 
D2

  name  Age
0    A   22
1    B   25

In [7]:
D2.index

RangeIndex(start=0, stop=2, step=1)

In [8]:
D2.columns

Index(['name', 'Age'], dtype='object')

# Lecture 3 Creating DF

In [10]:
D1 = pd.DataFrame ( [
    ["A",22],
    ["B",33] ,
    ["C",44]
] , columns = ["Name" , "Age"] )
D1

  Name  Age
0    A   22
1    B   33
2    C   44

In [12]:
import numpy as np 

A = np.array ([[1,2] ,
              [3,4]]) 
D2 = pd.DataFrame (A , columns = ["ID" ,"Marks"])

D2

   ID  Marks
0   1      2
1   3      4

In [ ]:
import sqlite3

C = sqlite3.connect ("DBname.sqlite")

D3 = pd.read_sql ("query" , C)

In [22]:
D5 = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
D5

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [23]:
D5.head ()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [24]:
D5.tail ()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [25]:
D5.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [26]:
D5.describe ()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [27]:
D5.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [28]:
D5.shape

(244, 7)

# LECTURE 4 selection and filtering

In [33]:
Data = pd.read_csv ("Movie.csv") 
Data.columns = Data.columns.str.strip ()

In [34]:
Data ["Actor"]

0      shak ruk khan
1        salmankhan
2         Amir khan
3      Ranvir kapoor
4    Ayushman kurana
5     Rajkummar rao
6      Hritik Roshan
7       Akshay Kumar
8      Kartik Aaryan
9         VsrunDawan
Name: Actor, dtype: object

In [35]:
Data [["Actor" , "Film"]]

             Actor                Film
0    shak ruk khan              Pathan
1      salmankhan     Tiger zindya he
2       Amir khan               Dangal
3    Ranvir kapoor              Animan
4  Ayushman kurana            Padmawat
5   Rajkummar rao                Stree
6    Hritik Roshan                 War
7     Akshay Kumar          Good Newaz
8    Kartik Aaryan      bhool boolya 2
9       VsrunDawan  Badhri ki dulaniya

In [36]:
Data .loc [0]

Actor                    shak ruk khan
Film                            Pathan
Year                              2023
Gener                          Action
Box Office (NR Cross)             1050
IMDB                               7.2
Name: 0, dtype: object

In [37]:
Data.iloc [0]

Actor                    shak ruk khan
Film                            Pathan
Year                              2023
Gener                          Action
Box Office (NR Cross)             1050
IMDB                               7.2
Name: 0, dtype: object

In [38]:
Data.iloc [0 , 4 ]

np.int64(1050)

In [39]:
Data

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
2,Amir khan,Dangal,2016,Biological,2024,9.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8

In [40]:
Data .loc [0:4 , "Actor":"Gener" ]

             Actor              Film  Year        Gener
0    shak ruk khan            Pathan  2023      Action
1      salmankhan   Tiger zindya he   2017      Action
2       Amir khan             Dangal  2016   Biological
3    Ranvir kapoor            Animan  2022     Fantasy
4  Ayushman kurana          Padmawat  2018  Historical

In [41]:
Data.iloc [0:4 , 0:4]

           Actor              Film  Year       Gener
0  shak ruk khan            Pathan  2023     Action
1    salmankhan   Tiger zindya he   2017     Action
2     Amir khan             Dangal  2016  Biological
3  Ranvir kapoor            Animan  2022    Fantasy

In [42]:
Data.at [3, "Film"]

'Animan'

In [43]:
Data [Data ["IMDB"] > 8 ]

            Actor    Film  Year       Gener  Box Office (NR Cross)  IMDB
2      Amir khan   Dangal  2016  Biological                   2024   9.2
3   Ranvir kapoor  Animan  2022    Fantasy                     431   9.0
5  Rajkummar rao    Stree  2018      Horror                    111   8.2

In [47]:
Data [(Data ["Year"] > 2018) & (Data ["IMDB"] > 7)]

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
6,Hritik Roshan,War,2019,Action,180,7.6
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7

In [48]:
Data.query ("Year > 2018 and IMDB > 7 ")

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
6,Hritik Roshan,War,2019,Action,180,7.6
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7

In [49]:
A = "Year"
Data.query(f"{A} > 2017")

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7

In [50]:
A = 2017
Data.query ("Year > @A")

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7

In [52]:
Data.query ("`Box Office (NR Cross)` > 600")

           Actor    Film  Year       Gener  Box Office (NR Cross)  IMDB
0  shak ruk khan  Pathan  2023     Action                    1050   7.2
2     Amir khan   Dangal  2016  Biological                   2024   9.2

# Lecture 5 : Data Cleaning

In [54]:
Data = pd.read_csv ("data_cleaning_sample.csv") 
Data

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [55]:
Data.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [57]:
Data.isnull ().sum ()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [58]:
Data.dropna ()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [59]:
Data.dropna (axis = 1)

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [60]:
Data.fillna (0)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [61]:
Data["Age"].fillna (Data ["Age"].mean ()  )

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [62]:
Data .fillna (method = "ffill")

C:\Users\PRANAV\AppData\Local\Temp\ipykernel_17892\1595818950.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  Data .fillna (method = "ffill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [64]:
Data.fillna (method = "bfill" )

C:\Users\PRANAV\AppData\Local\Temp\ipykernel_17892\3200939432.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  Data.fillna (method = "bfill" )

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [65]:
Data.ffill ()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [66]:
Data .bfill ()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [67]:
Data.dropna (inplace = True)

In [68]:
Data

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [72]:
Data.duplicated (["Name"])

0    False
2    False
4    False
6     True
7     True
dtype: bool

In [74]:
Data.drop_duplicates ()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019

In [76]:
Data["Gender"].str.contains ("F" )

0     True
2    False
4    False
6     True
7     True
Name: Gender, dtype: bool

In [83]:
Data ["Age"].astype (int) 
Data

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [90]:
Data["Date"] = pd.to_datetime (Data ["Join Date"],
                              format = "%d-%m-%Y",
                              errors = "coerce")
Data

    Name   Age         City Gender              Email   Join Date       Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021 2021-05-01
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020 2020-06-15
4  David  22.0       Mumbai      M  david@example.com  12-11-2019 2019-11-12
6  Alice  25.0     New York      F  alice@example.com  01-05-2021 2021-05-01
7  Alice  25.0     New York      F  alice@example.com  01-05-2021 2021-05-01

In [91]:
Data ["Age Group"] = Data["Age"].apply (lambda x :"Adult" if x > 24 else "Minor")

In [92]:
Data

,Name,Age,City,Gender,Email,Join Date,Date,Age Group
0,Alice,25.0,New York,F,alice@example.com,01-05-2021,2021-05-01,Adult
2,Bob,30.0,Los Angeles,M,bob@example.com,15-06-2020,2020-06-15,Adult
4,David,22.0,Mumbai,M,david@example.com,12-11-2019,2019-11-12,Minor
6,Alice,25.0,New York,F,alice@example.com,01-05-2021,2021-05-01,Adult
7,Alice,25.0,New York,F,alice@example.com,01-05-2021,2021-05-01,Adult

In [93]:
Data["Gender"] = Data["Gender"].map ({"F" : "Female" ,
                                     "M" : "Male"})

In [94]:
Data

,Name,Age,City,Gender,Email,Join Date,Date,Age Group
0,Alice,25.0,New York,Female,alice@example.com,01-05-2021,2021-05-01,Adult
2,Bob,30.0,Los Angeles,Male,bob@example.com,15-06-2020,2020-06-15,Adult
4,David,22.0,Mumbai,Male,david@example.com,12-11-2019,2019-11-12,Minor
6,Alice,25.0,New York,Female,alice@example.com,01-05-2021,2021-05-01,Adult
7,Alice,25.0,New York,Female,alice@example.com,01-05-2021,2021-05-01,Adult

In [95]:
Data ["City"]= Data ["City"].replace ({"New York" : "York" , "Mumbai" :"Navi Mumbai"})

In [96]:
Data

,Name,Age,City,Gender,Email,Join Date,Date,Age Group
0,Alice,25.0,York,Female,alice@example.com,01-05-2021,2021-05-01,Adult
2,Bob,30.0,Los Angeles,Male,bob@example.com,15-06-2020,2020-06-15,Adult
4,David,22.0,Navi Mumbai,Male,david@example.com,12-11-2019,2019-11-12,Minor
6,Alice,25.0,York,Female,alice@example.com,01-05-2021,2021-05-01,Adult
7,Alice,25.0,York,Female,alice@example.com,01-05-2021,2021-05-01,Adult

# Lecture 6 Data Transformation

In [103]:
Data = pd .read_csv ("Movie.csv") 
Data.columns = Data.columns.str.strip () 
Data

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
2,Amir khan,Dangal,2016,Biological,2024,9.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8

In [104]:
Data.sort_values (["Year" , "IMDB"] , ascending = False )

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
5,Rajkummar rao,Stree,2018,Horror,111,8.2
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8
2,Amir khan,Dangal,2016,Biological,2024,9.2

In [105]:
Data.reset_index (drop = True , inplace = True)
Data

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
2,Amir khan,Dangal,2016,Biological,2024,9.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8

In [106]:
Data .sort_index ()

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
2,Amir khan,Dangal,2016,Biological,2024,9.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8

In [108]:

Data["Score"] = Data ["Year"].rank (ascending = True , method = "dense")

In [109]:
Data

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB,Score
0,shak ruk khan,Pathan,2023,Action,1050,7.2,6.0
1,salmankhan,Tiger zindya he,2017,Action,565,8.0,2.0
2,Amir khan,Dangal,2016,Biological,2024,9.2,1.0
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0,5.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0,3.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2,3.0
6,Hritik Roshan,War,2019,Action,180,7.6,4.0
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7,4.0
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7,5.0
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8,2.0

In [110]:
Data["Year"].dtype

dtype('int64')

In [112]:
Data.rename (columns = {"Actor" : "Name" , "Film" :"Picture"})

,Name,Picture,Year,Gener,Box Office (NR Cross),IMDB,Score
0,shak ruk khan,Pathan,2023,Action,1050,7.2,6.0
1,salmankhan,Tiger zindya he,2017,Action,565,8.0,2.0
2,Amir khan,Dangal,2016,Biological,2024,9.2,1.0
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0,5.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0,3.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2,3.0
6,Hritik Roshan,War,2019,Action,180,7.6,4.0
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7,4.0
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7,5.0
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8,2.0

In [113]:
Data.rename (index = {0 : "key1"})

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB,Score
key1,shak ruk khan,Pathan,2023,Action,1050,7.2,6.0
1,salmankhan,Tiger zindya he,2017,Action,565,8.0,2.0
2,Amir khan,Dangal,2016,Biological,2024,9.2,1.0
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0,5.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0,3.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2,3.0
6,Hritik Roshan,War,2019,Action,180,7.6,4.0
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7,4.0
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7,5.0
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8,2.0

In [117]:
Data [["Year" , "Film" , "Actor"]]

   Year                Film            Actor
0  2023              Pathan    shak ruk khan
1  2017    Tiger zindya he       salmankhan
2  2016              Dangal       Amir khan
3  2022              Animan    Ranvir kapoor
4  2018            Padmawat  Ayushman kurana
5  2018               Stree   Rajkummar rao
6  2019                 War    Hritik Roshan
7  2019          Good Newaz     Akshay Kumar
8  2022      bhool boolya 2    Kartik Aaryan
9  2017  Badhri ki dulaniya       VsrunDawan

In [119]:
L = ["Year"] + [x for x in Data.columns if x != "Year"]

In [120]:
Data [L]

,Year,Actor,Film,Gener,Box Office (NR Cross),IMDB,Score
0,2023,shak ruk khan,Pathan,Action,1050,7.2,6.0
1,2017,salmankhan,Tiger zindya he,Action,565,8.0,2.0
2,2016,Amir khan,Dangal,Biological,2024,9.2,1.0
3,2022,Ranvir kapoor,Animan,Fantasy,431,9.0,5.0
4,2018,Ayushman kurana,Padmawat,Historical,585,8.0,3.0
5,2018,Rajkummar rao,Stree,Horror,111,8.2,3.0
6,2019,Hritik Roshan,War,Action,180,7.6,4.0
7,2019,Akshay Kumar,Good Newaz,Comedy,318,6.7,4.0
8,2022,Kartik Aaryan,bhool boolya 2,Comedy Horror,166,7.7,5.0
9,2017,VsrunDawan,Badhri ki dulaniya,Romantic comedy,201,4.8,2.0

# Lecture 7 melt and pivot

In [126]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 82, 89],
    'English': [88, 85, 94]
}

Data = pd.DataFrame(data)

# Display the DataFrame
print(Data)
Data.columns = Data.columns.str.strip()

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

In [131]:
Data = Data.melt (id_vars = "Name" , value_vars = ["Math","Science","English"] , var_name = "Subject" , value_name = "Score")

In [132]:
Data.pivot (index = "Name" , columns = "Subject" , values = "Score" )

Subject  English  Math  Science
Name
Alice         88    85       90
Bob           85    78       82
Charlie       94    92       89

In [133]:
Data

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

In [134]:
Data.loc [9] = ["Alice" , "MAth" , 99]

In [135]:
Data

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94
9    Alice     MAth     99

In [140]:
Data.pivot_table (index = "Name" , columns = "Subject" , values = "Score" , aggfunc = "mean")

Subject  English  MAth  Math  Science
Name
Alice       88.0  99.0  85.0     90.0
Bob         85.0   NaN  78.0     82.0
Charlie     94.0   NaN  92.0     89.0

# Lecture 8 groupby with aggfunc

In [142]:
Data = pd.DataFrame({
    "Department": ["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales"],
    "Team": ["A", "A", "B", "B", "C", "C", "D", "D"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Salary": [85, 90, 78, 85, 92, 88, 75, 80],
    "Age": [23, 25, 30, 22, 28, 26, 21, 27],
    "JoinDate": pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20", "2021-04-10",
        "2020-05-30", "2020-06-25", "2021-07-15", "2021-08-01"
    ])
})

In [143]:
Data

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    B      F      85   22 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      M      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

In [146]:
Data.groupby (["Department" , "Gender"])["Salary"].mean()

Department  Gender
HR          F         90.0
            M         85.0
IT          F         85.0
            M         78.0
Marketing   F         88.0
            M         92.0
Sales       F         80.0
            M         75.0
Name: Salary, dtype: float64

In [148]:
Data.groupby ("Team")["Salary"].agg (['mean' , 'max'])

      mean  max
Team
A     87.5   90
B     81.5   85
C     90.0   92
D     77.5   80

In [149]:
Data.groupby ("Team")["Salary"].agg (avg_Sal = "mean" ,
                                    max_sal = "max")

      avg_Sal  max_sal
Team
A        87.5       90
B        81.5       85
C        90.0       92
D        77.5       80

In [150]:
Data.groupby ("Team").agg ({
    "Salary" : "mean",
    "Age" : "max"
})

      Salary  Age
Team
A       87.5   25
B       81.5   30
C       90.0   28
D       77.5   27

In [152]:
Data ["Team Salary"] =  Data .groupby('Team') ["Salary"] .transform ("mean")

In [153]:
Data

  Department Team Gender  Salary  Age   JoinDate  Team Salary
0         HR    A      M      85   23 2020-01-10         87.5
1         HR    A      F      90   25 2020-02-15         87.5
2         IT    B      M      78   30 2021-03-20         81.5
3         IT    B      F      85   22 2021-04-10         81.5
4  Marketing    C      M      92   28 2020-05-30         90.0
5  Marketing    C      F      88   26 2020-06-25         90.0
6      Sales    D      M      75   21 2021-07-15         77.5
7      Sales    D      F      80   27 2021-08-01         77.5

In [156]:
Data.groupby ("Department") .filter (lambda x : x["Salary"].mean () != "M")

  Department Team Gender  Salary  Age   JoinDate  Team Salary
0         HR    A      M      85   23 2020-01-10         87.5
1         HR    A      F      90   25 2020-02-15         87.5
2         IT    B      M      78   30 2021-03-20         81.5
3         IT    B      F      85   22 2021-04-10         81.5
4  Marketing    C      M      92   28 2020-05-30         90.0
5  Marketing    C      F      88   26 2020-06-25         90.0
6      Sales    D      M      75   21 2021-07-15         77.5
7      Sales    D      F      80   27 2021-08-01         77.5

# Lecture 9 merge and concat

In [157]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [158]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [159]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [160]:
pd.merge (employees , departments , on = "DeptID")

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [165]:
pd.merge (employees , departments , on = "DeptID",  how= "outer")

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [168]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})

In [170]:
pd.concat ([df1,df2])

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [171]:
pd.concat ([df1 , df2 ],axis = 1)

    Name     Name
0  Alice  Charlie
1    Bob    David

# Lecture 10 : Working with file

In [174]:
Data.to_csv ("A.csv" , index = False )

In [177]:
Data.to_excel ("A.xlsx" , sheet_name ="S1")

In [178]:
df1.to_excel ("A.xlsx" , sheet_name = "S2")

In [182]:
D1 = pd.read_excel ("A.xlsx" , sheet_name = "S2")
D1

   Unnamed: 0   Name
0           0  Alice
1           1    Bob

In [187]:
with pd.ExcelWriter ("A.xlsx") as E : 
    df1.to_excel (E , sheet_name = "S3")
    df2.to_excel (E , sheet_name = "S4")