# Lecture 1

In [1]:
import pandas as pd

# Lecture 2

In [2]:
D1 = pd.Series ([1,2] , index = ["A","B"]) 
D1

A    1
B    2
dtype: int64

In [3]:
D2 = pd.DataFrame ({
    "Name": ["a", "b","c"] ,
    "Age" : [34,34,32]
})
D2

  Name  Age
0    a   34
1    b   34
2    c   32

In [4]:
D2.columns

Index(['Name', 'Age'], dtype='object')

In [5]:
D2.index

RangeIndex(start=0, stop=3, step=1)

# Lecture 3

In [8]:
D1 = pd.DataFrame ([["A" , 20],
                   ["B" , 30]] , columns = ["Name","Age"])
D1

  Name  Age
0    A   20
1    B   30

In [10]:
import numpy as np
A = np.array ([[2,5],
              [1,4]])
D2 = pd.DataFrame (A , columns = ["A","B"]) 
D2

   A  B
0  2  5
1  1  4

In [11]:
Data = pd.read_csv ("Movie.csv")

In [12]:
Data.head ()

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
2,Amir khan,Dangal,2016,Biological,2024,9.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0

In [13]:
Data.tail ()

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8

In [14]:
Data.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Actor                  10 non-null     object
 1   Film                   10 non-null     object
 2   Year                   10 non-null     int64
 3   Gener                  10 non-null     object
 4   Box Office (NR Cross)  10 non-null     int64
 5   IMDB                   10 non-null     float64
dtypes: float64(1), int64(2), object(3)
memory usage: 612.0+ bytes

In [15]:
Data.describe ()

             Year   Box Office (NR Cross)       IMDB
count    10.000000              10.000000  10.000000
mean   2019.100000             563.100000   7.640000
std       2.424413             585.877585   1.247397
min    2016.000000             111.000000   4.800000
25%    2017.250000             185.250000   7.300000
50%    2018.500000             374.500000   7.850000
75%    2021.250000             580.000000   8.150000
max    2023.000000            2024.000000   9.200000

In [16]:
Data.columns

Index(['Actor ', 'Film', 'Year ', 'Gener', 'Box Office (NR Cross)', 'IMDB'], dtype='object')

In [17]:
Data.shape

(10, 6)

# Lecture 4

In [20]:
Data.columns = Data.columns.str.strip () 
Data [["Actor" , "Film" , "Year" ]]

             Actor                Film  Year
0    shak ruk khan              Pathan  2023
1      salmankhan     Tiger zindya he   2017
2       Amir khan               Dangal  2016
3    Ranvir kapoor              Animan  2022
4  Ayushman kurana            Padmawat  2018
5   Rajkummar rao                Stree  2018
6    Hritik Roshan                 War  2019
7     Akshay Kumar          Good Newaz  2019
8    Kartik Aaryan      bhool boolya 2  2022
9       VsrunDawan  Badhri ki dulaniya  2017

In [21]:
Data.loc [0]

Actor                    shak ruk khan
Film                            Pathan
Year                              2023
Gener                          Action
Box Office (NR Cross)             1050
IMDB                               7.2
Name: 0, dtype: object

In [22]:
Data.loc [0,"Actor"]

'shak ruk khan'

In [24]:
Data.loc [0 , ["Actor" , "Film"]]

Actor    shak ruk khan
Film            Pathan
Name: 0, dtype: object

In [25]:
Data.loc [0:3 , "Actor":"Year"]

           Actor              Film  Year
0  shak ruk khan            Pathan  2023
1    salmankhan   Tiger zindya he   2017
2     Amir khan             Dangal  2016
3  Ranvir kapoor            Animan  2022

In [26]:
Data.at [5 , "Film"]

'Stree'

In [28]:
Data [Data["Year"] >= 2019 ]

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7

In [30]:
Data [(Data ["Year"] > 20) & (Data["IMDB"]> 8)]

            Actor    Film  Year       Gener  Box Office (NR Cross)  IMDB
2      Amir khan   Dangal  2016  Biological                   2024   9.2
3   Ranvir kapoor  Animan  2022    Fantasy                     431   9.0
5  Rajkummar rao    Stree  2018      Horror                    111   8.2

In [31]:

a = "Year"
b = 2017
Data.query (f"{a} > @b")

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7

# Lecture 5

In [32]:
D1 = pd.read_csv ("data_cleaning_sample.csv")

In [34]:
D1.isnull ().sum ()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [36]:
D1.dropna (axis =1 )

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [40]:
D1.fillna (method = "bfill")

C:\Users\PRANAV\AppData\Local\Temp\ipykernel_3476\3086510020.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  D1.fillna (method = "bfill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [43]:
D1.dropna (inplace = True)

In [44]:
D1

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [46]:
D1.duplicated (["Name" , "Age"])

0    False
2    False
4    False
6     True
7     True
dtype: bool

In [52]:
D1.drop_duplicates ()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019

In [54]:
D1["Gender"].str.contains ("F" , case = False)

0     True
2    False
4    False
6     True
7     True
Name: Gender, dtype: bool

In [55]:
D1["Age"] = D1["Age"].astype (int)

In [57]:
D1["Date"] = pd.to_datetime (D1["Join Date"] ,
                            format = "%d-%m-%Y" ,
                            errors = "coerce")

In [58]:
D1

    Name  Age         City Gender              Email   Join Date       Date
0  Alice   25     New York      F  alice@example.com  01-05-2021 2021-05-01
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020 2020-06-15
4  David   22       Mumbai      M  david@example.com  12-11-2019 2019-11-12
6  Alice   25     New York      F  alice@example.com  01-05-2021 2021-05-01
7  Alice   25     New York      F  alice@example.com  01-05-2021 2021-05-01

In [59]:
D1["Age Catagory"] = D1["Age"].apply (lambda x : "Adult" if x > 25 else "Minor")

In [61]:
D1["Gender"] = D1["Gender"]. map ({
    "F" : "Female",
    "M" : "Male"
}) 
D1

,Name,Age,City,Gender,Email,Join Date,Date,Age Catagory
0,Alice,25,New York,Female,alice@example.com,01-05-2021,2021-05-01,Minor
2,Bob,30,Los Angeles,Male,bob@example.com,15-06-2020,2020-06-15,Adult
4,David,22,Mumbai,Male,david@example.com,12-11-2019,2019-11-12,Minor
6,Alice,25,New York,Female,alice@example.com,01-05-2021,2021-05-01,Minor
7,Alice,25,New York,Female,alice@example.com,01-05-2021,2021-05-01,Minor

In [63]:
D1["City"] = D1 ["City"].replace ({
    "New York" : "York",
    "Mumbai" : "Navi Mumbai"
 }) 
D1

,Name,Age,City,Gender,Email,Join Date,Date,Age Catagory
0,Alice,25,York,Female,alice@example.com,01-05-2021,2021-05-01,Minor
2,Bob,30,Los Angeles,Male,bob@example.com,15-06-2020,2020-06-15,Adult
4,David,22,Navi Mumbai,Male,david@example.com,12-11-2019,2019-11-12,Minor
6,Alice,25,York,Female,alice@example.com,01-05-2021,2021-05-01,Minor
7,Alice,25,York,Female,alice@example.com,01-05-2021,2021-05-01,Minor

# Lecture 6

In [67]:
Data = pd.read_csv ("Movie.csv")
Data.columns = Data.columns.str.strip ()

In [75]:
Data.sort_values (["Year" , "IMDB"],ascending = False , inplace = True)

In [76]:
Data.sort_index ()

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
2,Amir khan,Dangal,2016,Biological,2024,9.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8

In [77]:
Data.reset_index (drop = True , inplace = True)

In [78]:
Data

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
2,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
3,Hritik Roshan,War,2019,Action,180,7.6
4,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Ayushman kurana,Padmawat,2018,Historical,585,8.0
7,salmankhan,Tiger zindya he,2017,Action,565,8.0
8,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8
9,Amir khan,Dangal,2016,Biological,2024,9.2

In [79]:
Data ["Rank"] = Data["Year"].rank (ascending = False , method = 'dense')

In [80]:
Data

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB,Rank
0,shak ruk khan,Pathan,2023,Action,1050,7.2,1.0
1,Ranvir kapoor,Animan,2022,Fantasy,431,9.0,2.0
2,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7,2.0
3,Hritik Roshan,War,2019,Action,180,7.6,3.0
4,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7,3.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2,4.0
6,Ayushman kurana,Padmawat,2018,Historical,585,8.0,4.0
7,salmankhan,Tiger zindya he,2017,Action,565,8.0,5.0
8,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8,5.0
9,Amir khan,Dangal,2016,Biological,2024,9.2,6.0

In [82]:
Data.rename (columns = {"Actor": "name"} , inplace = True)

In [83]:
Data.rename (index = {0 : "Row 1"} , inplace = True)

In [84]:
Data

,name,Film,Year,Gener,Box Office (NR Cross),IMDB,Rank
Row 1,shak ruk khan,Pathan,2023,Action,1050,7.2,1.0
1,Ranvir kapoor,Animan,2022,Fantasy,431,9.0,2.0
2,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7,2.0
3,Hritik Roshan,War,2019,Action,180,7.6,3.0
4,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7,3.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2,4.0
6,Ayushman kurana,Padmawat,2018,Historical,585,8.0,4.0
7,salmankhan,Tiger zindya he,2017,Action,565,8.0,5.0
8,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8,5.0
9,Amir khan,Dangal,2016,Biological,2024,9.2,6.0

In [86]:
Data [["Gener" , "name" , "Rank"]]

                 Gener             name  Rank
Row 1          Action     shak ruk khan   1.0
1             Fantasy     Ranvir kapoor   2.0
2        Comedy Horror    Kartik Aaryan   2.0
3              Action     Hritik Roshan   3.0
4              Comedy      Akshay Kumar   3.0
5               Horror   Rajkummar rao    4.0
6          Historical   Ayushman kurana   4.0
7              Action       salmankhan    5.0
8      Romantic comedy       VsrunDawan   5.0
9           Biological       Amir khan    6.0

# Lecture 7

In [88]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 82, 89],
    'English': [88, 85, 94]
}

Data = pd.DataFrame(data)

# Display the DataFrame
print(Data)

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

In [94]:
Data =Data.melt (id_vars = ["Name"] ,value_vars = ['Math','Science','English'] , var_name ="Subject" , value_name = "Score" )

In [95]:
Data.pivot (index = "Name" , columns = "Subject" , values = "Score")

Subject  English  Math  Science
Name
Alice         88    85       90
Bob           85    78       82
Charlie       94    92       89

In [96]:
Data

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

In [97]:
Data.loc[9] = ["Alice" , "Math", 80]

In [101]:
Data.pivot_table (index = "Name" , columns = "Subject" ,values = "Score" ,aggfunc = "max")

Subject  English  Math  Science
Name
Alice         88    85       90
Bob           85    78       82
Charlie       94    92       89

# Lecture 8

In [104]:
Data = pd.DataFrame({
    "Department": ["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales"],
    "Team": ["A", "A", "B", "B", "C", "C", "D", "D"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Salary": [85, 90, 78, 85, 92, 88, 75, 80],
    "Age": [23, 25, 30, 22, 28, 26, 21, 27],
    "JoinDate": pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20", "2021-04-10",
        "2020-05-30", "2020-06-25", "2021-07-15", "2021-08-01"
    ])
})

In [105]:
Data

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    B      F      85   22 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      M      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

In [108]:
Data.groupby (["Department" , "Gender"] )["Salary"].max ()

Department  Gender
HR          F         90
            M         85
IT          F         85
            M         78
Marketing   F         88
            M         92
Sales       F         80
            M         75
Name: Salary, dtype: int64

In [111]:
Data.groupby ("Department") ["Salary"] .agg (["mean" ,"max" , "min"]
                                            )

            mean  max  min
Department
HR          87.5   90   85
IT          81.5   85   78
Marketing   90.0   92   88
Sales       77.5   80   75

In [112]:
Data.groupby ("Team") ["Salary"] .agg (Avg_sal = "mean" ,
                                      Max_sal = "max")

      Avg_sal  Max_sal
Team
A        87.5       90
B        81.5       85
C        90.0       92
D        77.5       80

In [113]:
Data.groupby ("Team").agg ({
    "Salary": "mean",
    "Age" : "max"
})

      Salary  Age
Team
A       87.5   25
B       81.5   30
C       90.0   28
D       77.5   27

In [117]:
Data["Rank"] = Data.groupby ("Department") ['Age'].transform ("max")

In [118]:
Data

  Department Team Gender  Salary  Age   JoinDate  Rank
0         HR    A      M      85   23 2020-01-10    25
1         HR    A      F      90   25 2020-02-15    25
2         IT    B      M      78   30 2021-03-20    30
3         IT    B      F      85   22 2021-04-10    30
4  Marketing    C      M      92   28 2020-05-30    28
5  Marketing    C      F      88   26 2020-06-25    28
6      Sales    D      M      75   21 2021-07-15    27
7      Sales    D      F      80   27 2021-08-01    27

In [124]:
Data .groupby("Team").filter (lambda x : x["Salary"].max () >90)

  Department Team Gender  Salary  Age   JoinDate  Rank
4  Marketing    C      M      92   28 2020-05-30    28
5  Marketing    C      F      88   26 2020-06-25    28

# Lecture 9

In [125]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [126]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [127]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [131]:
pd.merge (employees , departments , on = "DeptID" , how = "outer")

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [132]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})

pd.concat([df1, df2])

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [133]:
pd.concat ([df1,df2] , axis = 1 )

    Name     Name
0  Alice  Charlie
1    Bob    David

In [134]:
D1

,Name,Age,City,Gender,Email,Join Date,Date,Age Catagory
0,Alice,25,York,Female,alice@example.com,01-05-2021,2021-05-01,Minor
2,Bob,30,Los Angeles,Male,bob@example.com,15-06-2020,2020-06-15,Adult
4,David,22,Navi Mumbai,Male,david@example.com,12-11-2019,2019-11-12,Minor
6,Alice,25,York,Female,alice@example.com,01-05-2021,2021-05-01,Minor
7,Alice,25,York,Female,alice@example.com,01-05-2021,2021-05-01,Minor

# Lecture 10

In [135]:
D1.to_excel ("A.xlsx" , sheet_name = "S1")

In [136]:
D2 = pd.read_excel ("A.xlsx" , sheet_name = "S1")

In [140]:
with pd.ExcelWriter ("B.xlsx")  as E :
    D1.to_excel (E , sheet_name = "S1")