In [1]:
import pandas as pd

In [2]:
Data = pd.read_csv ("Movie.csv")

In [5]:
Data.columns = Data.columns.str.strip ()

In [8]:
Data.sort_values (["Year" ,"IMDB"] , ascending = False , inplace = True)

In [7]:
Data.sort_index ()

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
2,Amir khan,Dangal,2016,Biological,2024,9.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8

In [9]:
Data

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
3,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
8,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
6,Hritik Roshan,War,2019,Action,180,7.6
7,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
5,Rajkummar rao,Stree,2018,Horror,111,8.2
4,Ayushman kurana,Padmawat,2018,Historical,585,8.0
1,salmankhan,Tiger zindya he,2017,Action,565,8.0
9,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8
2,Amir khan,Dangal,2016,Biological,2024,9.2

In [11]:
Data.reset_index (drop = True ,  inplace= True)

In [12]:
Data

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB
0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
2,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
3,Hritik Roshan,War,2019,Action,180,7.6
4,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
5,Rajkummar rao,Stree,2018,Horror,111,8.2
6,Ayushman kurana,Padmawat,2018,Historical,585,8.0
7,salmankhan,Tiger zindya he,2017,Action,565,8.0
8,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8
9,Amir khan,Dangal,2016,Biological,2024,9.2

In [13]:
Data["Rank"] = Data["IMDB"].rank ()

In [16]:
Data["Rank"] = Data ["IMDB"].rank (ascending=False , method = "dense")

In [17]:
Data

,Actor,Film,Year,Gener,Box Office (NR Cross),IMDB,Rank
0,shak ruk khan,Pathan,2023,Action,1050,7.2,7.0
1,Ranvir kapoor,Animan,2022,Fantasy,431,9.0,2.0
2,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7,5.0
3,Hritik Roshan,War,2019,Action,180,7.6,6.0
4,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2,3.0
6,Ayushman kurana,Padmawat,2018,Historical,585,8.0,4.0
7,salmankhan,Tiger zindya he,2017,Action,565,8.0,4.0
8,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8,9.0
9,Amir khan,Dangal,2016,Biological,2024,9.2,1.0

In [19]:
Data.rename (columns = {"Actor" : "Name"}, inplace = True)

In [22]:
Data.rename (index = {0 : "Key 0"} , inplace = True)

In [23]:
Data

,Name,Film,Year,Gener,Box Office (NR Cross),IMDB,Rank
Key 0,shak ruk khan,Pathan,2023,Action,1050,7.2,7.0
1,Ranvir kapoor,Animan,2022,Fantasy,431,9.0,2.0
2,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7,5.0
3,Hritik Roshan,War,2019,Action,180,7.6,6.0
4,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7,8.0
5,Rajkummar rao,Stree,2018,Horror,111,8.2,3.0
6,Ayushman kurana,Padmawat,2018,Historical,585,8.0,4.0
7,salmankhan,Tiger zindya he,2017,Action,565,8.0,4.0
8,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8,9.0
9,Amir khan,Dangal,2016,Biological,2024,9.2,1.0

In [24]:
Data [["Name" , "Year","IMDB"]]

                  Name  Year  IMDB
Key 0    shak ruk khan  2023   7.2
1        Ranvir kapoor  2022   9.0
2        Kartik Aaryan  2022   7.7
3        Hritik Roshan  2019   7.6
4         Akshay Kumar  2019   6.7
5       Rajkummar rao   2018   8.2
6      Ayushman kurana  2018   8.0
7          salmankhan   2017   8.0
8           VsrunDawan  2017   4.8
9           Amir khan   2016   9.2

In [25]:
D = ["Rank"] + [x for x in Data.columns if x != "Rank"]

In [26]:
Data [D]

,Rank,Name,Film,Year,Gener,Box Office (NR Cross),IMDB
Key 0,7.0,shak ruk khan,Pathan,2023,Action,1050,7.2
1,2.0,Ranvir kapoor,Animan,2022,Fantasy,431,9.0
2,5.0,Kartik Aaryan,bhool boolya 2,2022,Comedy Horror,166,7.7
3,6.0,Hritik Roshan,War,2019,Action,180,7.6
4,8.0,Akshay Kumar,Good Newaz,2019,Comedy,318,6.7
5,3.0,Rajkummar rao,Stree,2018,Horror,111,8.2
6,4.0,Ayushman kurana,Padmawat,2018,Historical,585,8.0
7,4.0,salmankhan,Tiger zindya he,2017,Action,565,8.0
8,9.0,VsrunDawan,Badhri ki dulaniya,2017,Romantic comedy,201,4.8
9,1.0,Amir khan,Dangal,2016,Biological,2024,9.2