In [3]:
import pandas as pd

In [29]:
Data = pd.read_csv ("data_cleaning_sample.csv")

In [5]:
Data

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [6]:
Data.isnull ()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [7]:
Data.isnull ().sum ()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [9]:
Data .dropna (inplace = True)

In [15]:
Data.dropna (axis = 1)

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [17]:
Data.fillna (Data ["Age"].mean() )

        Name        Age         City Gender              Email   Join Date
0      Alice  25.000000     New York      F  alice@example.com  01-05-2021
1    Charlie  25.833333        Delhi      M    charlie@example  20-07-2021
2        Bob  30.000000  Los Angeles      M    bob@example.com  15-06-2020
3    Charlie  25.833333        Delhi      M    charlie@example  20-07-2021
4      David  22.000000       Mumbai      M  david@example.com  12-11-2019
5  25.833333  28.000000        Delhi      F     eve@domain.com   25.833333
6      Alice  25.000000     New York      F  alice@example.com  01-05-2021
7      Alice  25.000000     New York      F  alice@example.com  01-05-2021
8    Charlie  25.833333        Delhi      M    charlie@example  20-07-2021

In [19]:
Data.fillna (method = "ffill")

C:\Users\PRANAV\AppData\Local\Temp\ipykernel_19280\4215943608.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  Data.fillna (method = "ffill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [20]:
Data.fillna (method= "bfill")

C:\Users\PRANAV\AppData\Local\Temp\ipykernel_19280\2187147047.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  Data.fillna (method= "bfill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [21]:
Data.ffill ()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [22]:
Data.bfill ()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [23]:
Data.dropna (inplace = True)

In [24]:
Data

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [26]:
Data.reset_index (drop = True , inplace = True)

In [31]:
Data

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [30]:
Data.duplicated ()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [32]:
Data.drop_duplicates ()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [33]:
Data

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [43]:
Data.duplicated (subset = ["Name","Gender"])

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [37]:
Data["Name"] = Data['Name'].str.lower ()

In [38]:
Data

      Name   Age         City Gender              Email   Join Date
0    alice  25.0     New York      F  alice@example.com  01-05-2021
1  charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    david  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    alice  25.0     New York      F  alice@example.com  01-05-2021
7    alice  25.0     New York      F  alice@example.com  01-05-2021
8  charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [46]:
Data["City"].str.contains( "Delhi" )

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [50]:
Data["City"].str.upper ()

0       NEW YORK
1          DELHI
2    LOS ANGELES
3          DELHI
4         MUMBAI
5          DELHI
6       NEW YORK
7       NEW YORK
8          DELHI
Name: City, dtype: object

In [53]:
Data ['Age Group'] = Data["Age"].apply (lambda x :"Adult" if x > 25 else "Minor"  )

In [54]:
Data

      Name   Age         City Gender              Email   Join Date Age Group
0    alice  25.0     New York      F  alice@example.com  01-05-2021     Minor
1  charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
2      bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
4    david  22.0       Mumbai      M  david@example.com  12-11-2019     Minor
5      NaN  28.0        Delhi      F     eve@domain.com         NaN     Adult
6    alice  25.0     New York      F  alice@example.com  01-05-2021     Minor
7    alice  25.0     New York      F  alice@example.com  01-05-2021     Minor
8  charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor

In [56]:
Data ["Gender"] = Data["Gender"].map ({"F" : "Female",
                    "M" : "Male"})

In [57]:
Data

      Name   Age         City  Gender              Email   Join Date Age Group
0    alice  25.0     New York  Female  alice@example.com  01-05-2021     Minor
1  charlie   NaN        Delhi    Male    charlie@example  20-07-2021     Minor
2      bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     Adult
3  charlie   NaN        Delhi    Male    charlie@example  20-07-2021     Minor
4    david  22.0       Mumbai    Male  david@example.com  12-11-2019     Minor
5      NaN  28.0        Delhi  Female     eve@domain.com         NaN     Adult
6    alice  25.0     New York  Female  alice@example.com  01-05-2021     Minor
7    alice  25.0     New York  Female  alice@example.com  01-05-2021     Minor
8  charlie   NaN        Delhi    Male    charlie@example  20-07-2021     Minor

In [58]:
Data ["City"] = Data["City"].replace ({"Delhi" : "New Delhi" ,
                                      "Mumbai" : "navi mumbai"})

In [60]:
Data = Data.dropna ()